# Copyright (c) 2017 ChromaWay Inc. See README for license information.
version: '3.1'

services:

  postgres:
    image: chromaway/postgres:2.4.3-beta
    restart: always
    environment:
      POSTGRES_PASSWORD: postchain

  dev-preview:
    image: chromaway/dev-preview:0.7.0-b3
    restart: always
    ports:
      - 127.0.0.1:7740:7740
      - 127.0.0.1:30000:30000
    depends_on:
      - postgres

